# Generated by Django 4.2.4 on 2023-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_categoria_contenido_is_active_contenido_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='es_moderado',
            new_name='moderada',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
