# Generated by Django 4.2.4 on 2023-09-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_contenido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('rechazado', 'Rechazado'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
    ]
