# Generated by Django 4.2.4 on 2023-09-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_remove_contenido_likes_like_contenido_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contenido/images/'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='contenido/videos/'),
        ),
    ]
