# Generated by Django 4.2.4 on 2023-09-26 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0011_remove_contenido_likes_like_contenido_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
