# Generated by Django 4.2.4 on 2023-09-27 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenido', '0012_contenido_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionContenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('rechazado', 'Rechazado'), ('publicado', 'Publicado')], default='En revisión', max_length=20)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='contenido.contenido', verbose_name='Contenido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
