# Generated by Django 4.2.4 on 2023-09-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_versioncontenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versioncontenido',
            old_name='version',
            new_name='serial',
        ),
    ]
