# Generated by Django 4.2.4 on 2023-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0013_alter_contenido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='solo_suscriptores',
            field=models.BooleanField(default=False),
        ),
    ]
