# Generated by Django 4.2.4 on 2023-09-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0012_contenido_fecha'),
        ('contenido', '0014_alter_contenido_image'),
    ]

    operations = [
    ]
