# Generated by Django 4.2.4 on 2023-09-27 22:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_rename_version_versioncontenido_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versioncontenido',
            old_name='fecha',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='versioncontenido',
            old_name='serial',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='versioncontenido',
            name='user',
        ),
        migrations.AddField(
            model_name='contenido',
            name='ultima_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ultima_version', to='contenido.versioncontenido', verbose_name='Ultima versión'),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='contenido.contenido'),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
