# Generated by Django 4.2.4 on 2023-09-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_rename_fecha_versioncontenido_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='ultima_version',
        ),
    ]
