# Generated by Django 4.2.4 on 2023-09-29 15:02

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0015_merge_0012_contenido_fecha_0014_alter_contenido_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='video',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='contenido/videos', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
