# Generated by Django 4.2.4 on 2023-09-27 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenido', '0017_versioncontenido_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioncontenido',
            name='user',
        ),
        migrations.AddField(
            model_name='versioncontenido',
            name='user_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='contenido.contenido', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
