# Generated by Django 4.2.4 on 2023-10-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0017_remove_contenido_image_remove_contenido_video_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'permissions': [('puede_publicar_no_moderada', 'Puede publicar en categoria no moderada')]},
        ),
    ]
