# Generated by Django 4.2.4 on 2023-10-02 02:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0018_alter_contenido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
