# Generated by Django 4.2.4 on 2023-10-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_alter_contenido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontenido',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_version', to='contenido.categoria', verbose_name='Categoria'),
        ),
    ]
