# Generated by Django 4.2.4 on 2023-10-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0014_contenido_solo_suscriptores'),
        ('contenido', '0020_versioncontenido_categoria'),
    ]

    operations = [
    ]
