# Generated by Django 4.2.4 on 2023-10-02 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0021_merge_20231002_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'permissions': [('ver_borradores', 'Ver borradores'), ('ver_rechazados', 'Ver rechazados'), ('ver_revisiones', 'Ver revisiones'), ('ver_a_publicar', 'Ver contenidos a publicar'), ('ver_kanban', 'Ver kanban'), ('ver_todos_kanban', 'Ver todos kanban'), ('puede_publicar_rechazar', 'Puede publicar o rechazar'), ('ver_todos_borradores', 'Ver todos los borradores'), ('puede_publicar_no_moderado', 'Puede publicar en categoria no moderada')]},
        ),
    ]
