# Generated by Django 4.2.4 on 2023-10-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0019_alter_contenido_descripcion'),
        ('contenido', '0022_alter_contenido_options'),
    ]

    operations = [
    ]
