# Generated by Django 4.2.4 on 2023-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0024_alter_contenido_options_alter_contenido_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
