# Generated by Django 4.2.4 on 2023-10-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0023_merge_20231002_0542'),
        ('contenido', '0025_contenido_razon_rechazo'),
        ('contenido', '0026_versioncontenido_solo_suscriptores_and_more'),
    ]

    operations = [
    ]
