# Generated by Django 4.2.4 on 2023-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0027_merge_20231002_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenido',
            old_name='razon_rechazo',
            new_name='nota',
        ),
        migrations.AddField(
            model_name='contenido',
            name='resumen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='versioncontenido',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versioncontenido',
            name='resumen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('apublicar', 'A publicar'), ('rechazado', 'Rechazado'), ('publicado', 'Publicado'), ('inactivo', 'Inactivo')], default='En revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='versioncontenido',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
