# Generated by Django 4.2.4 on 2023-10-19 20:31

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0029_alter_contenido_resumen_alter_contenido_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='contenido/archivos')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='contenido.contenido')),
            ],
        ),
    ]
