# Generated by Django 4.2.4 on 2023-11-03 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0030_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'permissions': [('ver_borradores', 'Ver borradores'), ('ver_rechazados', 'Ver rechazados'), ('ver_revisiones', 'Ver revisiones'), ('ver_a_publicar', 'Ver contenidos a publicar'), ('ver_kanban', 'Ver kanban'), ('ver_todos_kanban', 'Ver todos kanban'), ('puede_publicar_rechazar', 'Puede publicar o rechazar'), ('puede_editar_aceptar', 'Puede editar o aceptar'), ('ver_todos_borradores', 'Ver todos los borradores'), ('puede_publicar_no_moderada', 'Puede publicar en categoria no moderada'), ('ver_versiones', 'Ver versiones'), ('ver_todos_versiones', 'Ver todos las versiones')]},
        ),
    ]
