# Generated by Django 4.2.4 on 2023-10-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0030_archivos'),
        ('contenido', '0031_alter_contenido_options'),
    ]

    operations = [
    ]
