# Generated by Django 4.2.4 on 2023-11-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0032_merge_0030_archivos_0031_alter_contenido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
