# Generated by Django 4.2.4 on 2023-12-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0033_alter_contenido_options_contenido_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='promedio_calificacion',
            field=models.FloatField(default=0.0),
        ),
    ]
