# Generated by Django 4.2.4 on 2023-08-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_alter_profile_localidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telephone',
        ),
    ]
