# Generated by Django 4.2.4 on 2023-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_address_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'contenido',
                'verbose_name_plural': 'contenido',
                'ordering': ['-id'],
            },
        ),
    ]
