# Generated by Django 4.2.4 on 2023-09-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
